development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://default:UOZaWDQjOttTRORuyzNxKaEpSGGUyLMt@redis.railway.internal:6379
  channel_prefix: message_me_production
